module.exports = {
	MESSAGE_TYPE_TEXT: 'text',
	MESSAGE_TYPE_IMAGE: 'image',
	MESSAGE_TYPE_IMAGEMAP: 'imagemap',
	MESSAGE_TYPE_VIDEO: 'video',
	MESSAGE_TYPE_AUDIO: 'audio',
	MESSAGE_TYPE_FILE: 'file',
	MESSAGE_TYPE_LOCATION: 'location',
	MESSAGE_TYPE_STICKER: 'sticker',
	MESSAGE_CONTENT_PROVIDER_TYPE_LINE: 'line',
	MESSAGE_CONTENT_PROVIDER_TYPE_EXTERNAL: 'external',
}
